name: Enza Di Lecce
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f0f1'
    - '#bbb277'
    - '#302e42'
    - '#4a5956'
    - '#a78051'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
