name: Enza Di Lecce
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f0f1'
    - '#bbb277'
    - '#302e42'
    - '#4a5956'
    - '#a78051'
  brandStrength: 0.8533179806545377
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
